<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>WindowsScreenTimeSetup</AssemblyName>
    <ApplicationIcon>..\WindowsScreenTimeApp\app.ico</ApplicationIcon>
    <Version>1.3.0</Version>
    <Authors>哈呼呼吗</Authors>
    <RepositoryUrl>https://github.com/ju070322/WindowsScreenTime</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\WindowsScreenTimeApp\package\WindowsScreenTime.exe" LogicalName="payload.WindowsScreenTime.exe" />
    <EmbeddedResource Include="..\WindowsScreenTimeApp\package\app.ico" LogicalName="payload.app.ico" />
    <EmbeddedResource Include="..\WindowsScreenTimeApp\package\app-icon.png" LogicalName="payload.app-icon.png" />
    <EmbeddedResource Include="..\WindowsScreenTimeApp\package\README.md" LogicalName="payload.README.md" />
    <EmbeddedResource Include="..\WindowsScreenTimeApp\package\uninstall.cmd" LogicalName="payload.uninstall.cmd" />
  </ItemGroup>

</Project>
