<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WindowsScreenTimeUninstall</AssemblyName>
    <ApplicationIcon>..\WindowsScreenTimeApp\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.4.1</Version>
    <Authors>哈呼呼吗</Authors>
  </PropertyGroup>

</Project>
